spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=postgres
spring.datasource.password=13042004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Default admin (created on startup if no users exist)
auth.default-admin.username=admin
auth.default-admin.email=admin@portfolio.local
auth.default-admin.password=admin123