spring.application.name=portfolio
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Portfolio
spring.datasource.username=postgres
spring.datasource.password=13042004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# OpenAPI / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.profiles.active=dev

# Multipart File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email SMTP Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pdkhang.dev@gmail.com
# Nhập mật khẩu ứng dụng gồm 16 ký tự viết liền (không có khoảng trắng hay dấu gạch ngang)
# Ví dụ: wpbwthfkskxuoukk
spring.mail.password=wpbwthfkskxuoukk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true