name: Deploy Backend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Backend Container
        run: |
          cd ~/portfolio-app/portfolio
          git fetch origin main
          git reset --hard origin/main
          cd ~/portfolio-app
          docker compose up -d --build --no-deps backend
